site_name: Treinamento DevOps AWS IaC
site_description: DevOps e Infraestrutura como Código na AWS
site_author: uiuqM
site_url: https://uiuqm.github.io/treinamento-devops-aws-iac-epic

theme:
  name: material

nav:
  - Home: apresentacao.md
  - Ementa: Plano de Ensino Iac AWS.md
  - encontro-01: encontro-01.md
